version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-task-api
    restart: always
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - .env
    volumes:
      - ${ATTACHMENTS_VOLUME_HOST}:/usr/src/app/attachments
      - ${LOGS_VOLUME_HOST}:/usr/src/app/logs
